version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/golang:1.11"
    parallelism: 3
    working_directory: "/go/src/github.com/rocklviv/isearch"
    steps:
      - checkout
      - run: |
          make test
      - run: |
          make build-multiarch