version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/golang:1.11"
    parallelism: 3
    working_directory: "/go/src/github.com/rocklviv/isearch"
    steps:
      - checkout
      - run: |
          make deps
          make test
      - run: |
          make build-multiarch
      - deploy_artifact:
        requires:
          - build
        filters:
          tags:
            only:
              - /^v.*/
          branches:
            ignore:
              - /.*/

  deploy_artifact:
    docker:
      - image: "circleci/golang:1.11"
    working_directory: "/go/src/github.com/rocklviv/isearch"
      steps:
        - checkout
          - run: |
              make deps
              make test
          - run: |
              make build-multiarch
          - run: |
              go get -u github.com/tcnksm/ghr
              ghr -t $GITHUB_TOKEN -u $GITHUB_USERNAME $CIRCLE_TAG /go/src/github.com/rocklviv/isearch/release