version: 2.1

jobs:
  build:
    docker:
      - image: "golang:1.11-alpine"
    parallelism: 3
    branches:
      only:
        - master
        - /rc-.*/
    steps:
      - make lint
      - make test
      - make build-multiarch